version: "3"
services:
  mysql-db:
    image: mysql:5.7.26
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
    volumes:
      - ./ext/mysql.conf.d/my.cnf:/etc/my.cnf
      - ./tmp/mysql:/var/lib/mysql
    tmpfs:
      - /tmp
    ports:
      - 3306:3306